#!/bin/bash

function recurse {
	declare -x INDEX=0 COUNT=$#
	[ $DEPTH -eq 0 ] && RCOUNT=$#

	for d in "$@"; do
		[ $DEPTH -eq 0 ] && ((RINDEX++))
		((INDEX++))
		d="${d%/}"
		[[ -d $d && -x $d && -r $d ]] || continue
		[[ $nocd ]] || cd "$d"
		((DEPTH++))
		((RUNS++))

		if [ ${#indir[*]} -gt 0 ]; then
			if [[ $nocd ]]; then
				dirs=(${indir[*]/#/$d/})
			else
				dirs=(${indir[*]})
			fi
		else
			if [[ $nocd ]]; then
				dirs=("$d"/*/)
			else
				dirs=(*/)
			fi
		fi
		if [ ${#exdir[*]} -gt 0 ]; then
			if [[ $nocd ]]; then
				exclude=(${exdir[*]/#/$d/})
			else
				exclude=(${exdir[*]})
			fi
			count=${#dirs[*]}
			for e in ${exclude[*]}; do
				i=0
				while [ $i -lt $count ]; do
					if [[ ${dirs[i]%/} == ${e%/} ]]; then
						unset 'dirs[i]'
						break
					fi
					((i++))
				done
			done
		fi

		DIR="$d"
		[[ $nocd ]] || CWD="${PWD#*$ROOT/}"
		printf "$script" | $program ${ARGS[*]}
		recurse "${dirs[@]}"
		((DEPTH--))
		[[ $nocd ]] || cd ..
	done
}

shopt -s nullglob

if [[ $1 == "--help" ]]; then
	cat <<-'EOF'
		usage: redo [.] [+include_glob ...] [-exclude_glob ...] [dir ...] < script
		variables: $DIR, $CWD, $COUNT, $INDEX, $DEPTH, $RUNS
		           $ROOT, $ARGS, $RCOUNT, $RINDEX
	EOF
	exit
fi
if [[ $1 == "--version" ]]; then
	echo "redo 1.0"
	echo "Copyright 2017 Bernhard Waldbrunner"
	exit
fi

indir=()
exdir=()
dirs=()
nocd=
export DIR CWD RCOUNT ARGS RINDEX=0 DEPTH=0 RUNS=0 ROOT="$PWD"

for arg in "$@"; do
	if [[ ${arg:0:1} == '-' ]]; then
		exdir[${#exdir[*]}]="${arg:1}"
	elif [[ ${arg:0:1} == '+' ]]; then
		indir[${#indir[*]}]="${arg:1}"
	elif [[ $arg == '.' ]]; then
		nocd=1
		CWD="."
	else
		dirs[${#dirs[*]}]="$arg"
	fi
done

[ ${#dirs[*]} -eq 0 ] && dirs=(*/)

IFS=$'\n' read program
script=$(</dev/stdin)
if [[ ${program:0:2} == '#!' ]]; then
	program=(${program:2})
	ARGS=(${program[@]:1})
	program=${program[@]:0:1}
else
	script="$program"$'\n'"$script"
	program=$SHELL
	args=
fi

IFS=$'\n' recurse "${dirs[@]}"
